name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["mac", "linux"]
      fail-fast: false

    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: build-${{ matrix.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            build-${{ matrix.os }}-go-

      - name: Build
        env:
          OS: ${{ matrix.os }}
          REF: ${{ github.sha }}
          VERSION: "dev-${{ github.sha }}"
        run: "./.github/workflows/build.sh"

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: "msg-${{matrix.os}}-${{github.sha}}.tgz"
          path: "msg-${{matrix.os}}-${{github.sha}}.tgz"